services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app123
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"

  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/appdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: app123

volumes:
  mysql_data:
